# -*- coding: utf-8 -*-
"""task3/cnn_baseline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYEFDWKtVu-cDCWHNKR90yESHoB9GFNU
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# =====================================================
# Device
# =====================================================

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", device)

# =====================================================
# CIFAR-10 Dataset
# =====================================================

transform = transforms.ToTensor()

train_dataset = datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transform
)

# =====================================================
# DataLoaders
# =====================================================

batch_size = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)

# =====================================================
# Tiny CNN
# =====================================================

class TinyCNN(nn.Module):

    def __init__(self, num_classes=10):
        super().__init__()

        # Input: (B, 3, 32, 32)

        self.conv1 = nn.Conv2d(
            3,
            32,
            kernel_size=3,
            padding=1
        )

        self.conv2 = nn.Conv2d(
            32,
            64,
            kernel_size=3,
            padding=1
        )

        self.conv3 = nn.Conv2d(
            64,
            128,
            kernel_size=3,
            padding=1
        )

        self.pool = nn.MaxPool2d(2, 2)

        # After 3 pooling operations:
        # 32x32 -> 16x16 -> 8x8 -> 4x4

        self.fc1 = nn.Linear(
            128 * 4 * 4,
            256
        )

        self.fc2 = nn.Linear(
            256,
            num_classes
        )

        self.dropout = nn.Dropout(0.3)

    def forward(self, x):

        x = self.pool(
            F.relu(
                self.conv1(x)
            )
        )

        x = self.pool(
            F.relu(
                self.conv2(x)
            )
        )

        x = self.pool(
            F.relu(
                self.conv3(x)
            )
        )

        # (B,128,4,4) -> (B,2048)
        x = x.flatten(1)

        x = self.dropout(
            F.relu(
                self.fc1(x)
            )
        )

        x = self.fc2(x)

        return x

# =====================================================
# Model
# =====================================================

model = TinyCNN().to(device)

# Verify dimensions

x, y = next(iter(train_loader))

x = x.to(device)

out = model(x)

print("Input shape :", x.shape)
print("Output shape:", out.shape)

# =====================================================
# Loss and Optimizer
# =====================================================

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3
)

# =====================================================
# Training
# =====================================================

num_epochs = 10
train_losses = []

train_accs = []

val_accs = []

for epoch in range(num_epochs):

    # -------------------------
    # Training
    # -------------------------

    model.train()

    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for x, y in train_loader:

        x = x.to(device)
        y = y.to(device)

        outputs = model(x)

        loss = criterion(outputs, y)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        train_loss += loss.item()

        _, predicted = outputs.max(1)

        train_total += y.size(0)

        train_correct += (
            predicted == y
        ).sum().item()

    train_acc = (
        100 * train_correct / train_total
    )

    # -------------------------
    # Validation
    # -------------------------

    model.eval()

    val_correct = 0
    val_total = 0

    with torch.no_grad():

        for x, y in test_loader:

            x = x.to(device)
            y = y.to(device)

            outputs = model(x)

            _, predicted = outputs.max(1)

            val_total += y.size(0)

            val_correct += (
                predicted == y
            ).sum().item()

    val_acc = (
        100 * val_correct / val_total
    )

    train_losses.append(
    train_loss / len(train_loader)
   )

    train_accs.append(train_acc)

    val_accs.append(val_acc)

    avg_train_loss = train_loss / len(train_loader)
    print(
          f"Epoch [{epoch+1}/{num_epochs}] "
          f"Loss: {avg_train_loss:.4f} "
          f"Train Acc: {train_acc:.2f}% "
          f"Val Acc: {val_acc:.2f}%"
      )

import matplotlib.pyplot as plt

epochs = range(1, num_epochs + 1)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)

plt.plot(
    epochs,
    train_losses,
    marker='o',
    label='Train Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.legend()

plt.subplot(1,2,2)

plt.plot(
    epochs,
    train_accs,
    marker='o',
    label='Train Accuracy'
)

plt.plot(
    epochs,
    val_accs,
    marker='o',
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("Training vs Validation Accuracy")
plt.legend()

plt.tight_layout()

plt.savefig(
    "cnn_training_curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# =====================================================
# Save Model
# =====================================================

torch.save(
    model.state_dict(),
    "tinycnn_cifar10.pth"
)

print("Model saved successfully.")