# -*- coding: utf-8 -*-
"""task5/clip_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xy9SCPXFmVlZsZDLaABIDgZD9XOcF4mC
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F


# ============================================================
# Device
# ============================================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ============================================================
# CLIP InfoNCE Loss
# ============================================================

class InfoNCELoss(nn.Module):
    """
    Symmetric CLIP loss with learnable temperature.
    """

    def __init__(self, init_temperature=0.07):
        super().__init__()

        self.logit_scale = nn.Parameter(
            torch.tensor(math.log(1 / init_temperature))
        )

    def forward(self, image_embeddings, text_embeddings):

        image_embeddings = F.normalize(image_embeddings, dim=-1)
        text_embeddings = F.normalize(text_embeddings, dim=-1)

        scale = self.logit_scale.exp().clamp(max=100)

        logits = scale * image_embeddings @ text_embeddings.t()

        labels = torch.arange(
            logits.size(0),
            device=logits.device
        )

        loss_i = F.cross_entropy(
            logits,
            labels
        )

        loss_t = F.cross_entropy(
            logits.t(),
            labels
        )

        return (loss_i + loss_t) / 2


# ============================================================
# Feed Forward Network
# ============================================================

class FeedForward(nn.Module):

    def __init__(
        self,
        embed_dim,
        dropout=0.1
    ):
        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(
                embed_dim,
                4 * embed_dim
            ),

            nn.GELU(),

            nn.Dropout(dropout),

            nn.Linear(
                4 * embed_dim,
                embed_dim
            ),

            nn.Dropout(dropout)

        )

    def forward(self, x):
        return self.net(x)


# ============================================================
# Multi Head Self Attention
# ============================================================

class MultiHeadSelfAttention(nn.Module):

    def __init__(
        self,
        embed_dim,
        n_head,
        dropout=0.1
    ):
        super().__init__()

        assert embed_dim % n_head == 0

        self.embed_dim = embed_dim
        self.n_head = n_head
        self.head_dim = embed_dim // n_head

        self.qkv = nn.Linear(
            embed_dim,
            embed_dim * 3
        )

        self.proj = nn.Linear(
            embed_dim,
            embed_dim
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        B, T, C = x.shape

        qkv = self.qkv(x)

        qkv = qkv.reshape(
            B,
            T,
            3,
            self.n_head,
            self.head_dim
        )

        qkv = qkv.permute(
            2,
            0,
            3,
            1,
            4
        )

        q, k, v = qkv

        attn = (
            q @ k.transpose(-2, -1)
        ) / math.sqrt(self.head_dim)

        attn = F.softmax(
            attn,
            dim=-1
        )

        attn = self.dropout(attn)

        out = attn @ v

        out = out.transpose(
            1,
            2
        ).reshape(
            B,
            T,
            C
        )

        out = self.proj(out)

        out = self.dropout(out)

        return out


# ============================================================
# Transformer Encoder Block
# ============================================================

class TransformerBlock(nn.Module):

    def __init__(
        self,
        embed_dim,
        n_head,
        dropout=0.1
    ):
        super().__init__()

        self.ln1 = nn.LayerNorm(embed_dim)

        self.attn = MultiHeadSelfAttention(
            embed_dim,
            n_head,
            dropout
        )

        self.ln2 = nn.LayerNorm(embed_dim)

        self.ffn = FeedForward(
            embed_dim,
            dropout
        )

    def forward(self, x):

        x = x + self.attn(
            self.ln1(x)
        )

        x = x + self.ffn(
            self.ln2(x)
        )

        return x

# ============================================================
# Vision Transformer
# ============================================================

class VisionTransformer(nn.Module):

    def __init__(
        self,
        img_size=64,
        patch_size=8,
        in_channels=3,
        embed_dim=192,
        n_head=6,
        n_layer=6,
        dropout=0.1,
    ):
        super().__init__()

        assert img_size % patch_size == 0

        self.img_size = img_size
        self.patch_size = patch_size

        self.num_patches = (
            img_size // patch_size
        ) ** 2

        self.patch_embed = nn.Conv2d(
            in_channels,
            embed_dim,
            kernel_size=patch_size,
            stride=patch_size
        )

        self.cls_token = nn.Parameter(
            torch.zeros(
                1,
                1,
                embed_dim
            )
        )

        self.pos_embedding = nn.Parameter(
            torch.randn(
                1,
                self.num_patches + 1,
                embed_dim
            ) * 0.02
        )

        self.dropout = nn.Dropout(dropout)

        self.blocks = nn.ModuleList(

            [
                TransformerBlock(
                    embed_dim,
                    n_head,
                    dropout
                )

                for _ in range(n_layer)

            ]

        )

        self.norm = nn.LayerNorm(
            embed_dim
        )

    def forward(self, images):

        B = images.size(0)

        x = self.patch_embed(images)

        # (B,C,H,W)
        # ->
        # (B,C,N)

        x = x.flatten(2)

        # ->
        # (B,N,C)

        x = x.transpose(1, 2)

        cls = self.cls_token.expand(
            B,
            -1,
            -1
        )

        x = torch.cat(
            [
                cls,
                x
            ],
            dim=1
        )

        x = x + self.pos_embedding

        x = self.dropout(x)

        for block in self.blocks:
            x = block(x)

        x = self.norm(x)

        return x


# ============================================================
# Text Transformer
# ============================================================

class TextTransformer(nn.Module):

    def __init__(
        self,
        vocab_size,
        max_length=32,
        embed_dim=192,
        n_head=6,
        n_layer=6,
        dropout=0.1,
    ):
        super().__init__()

        self.token_embedding = nn.Embedding(
            vocab_size,
            embed_dim
        )

        self.position_embedding = nn.Embedding(
            max_length,
            embed_dim
        )

        self.dropout = nn.Dropout(
            dropout
        )

        self.blocks = nn.ModuleList(

            [

                TransformerBlock(
                    embed_dim,
                    n_head,
                    dropout
                )

                for _ in range(n_layer)

            ]

        )

        self.norm = nn.LayerNorm(
            embed_dim
        )

    def forward(
        self,
        tokens
    ):

        B, T = tokens.shape

        positions = torch.arange(
            T,
            device=tokens.device
        )

        positions = positions.unsqueeze(0)

        x = (
            self.token_embedding(tokens)
            +
            self.position_embedding(positions)
        )

        x = self.dropout(x)

        for block in self.blocks:
            x = block(x)

        x = self.norm(x)

        return x

# ============================================================
# CLIP Style Model
# ============================================================

class CLIPStyleModel(nn.Module):

    def __init__(
        self,
        vocab_size,
        max_length=32,
        embed_dim=192,
        projection_dim=192,
        n_head=6,
        n_layer=6,
        dropout=0.1,
    ):
        super().__init__()

        self.vision_encoder = VisionTransformer(
            img_size=64,
            patch_size=8,
            embed_dim=embed_dim,
            n_head=n_head,
            n_layer=n_layer,
            dropout=dropout,
        )

        self.text_encoder = TextTransformer(
            vocab_size=vocab_size,
            max_length=max_length,
            embed_dim=embed_dim,
            n_head=n_head,
            n_layer=n_layer,
            dropout=dropout,
        )

        self.image_projection = nn.Linear(
            embed_dim,
            projection_dim,
            bias=False,
        )

        self.text_projection = nn.Linear(
            embed_dim,
            projection_dim,
            bias=False,
        )

        self.loss_fn = InfoNCELoss()

    # --------------------------------------------------------
    # Image Encoder
    # --------------------------------------------------------

    def encode_image(
        self,
        images
    ):

        features = self.vision_encoder(images)

        cls_feature = features[:, 0]

        embeddings = self.image_projection(
            cls_feature
        )

        embeddings = F.normalize(
            embeddings,
            dim=-1
        )

        return embeddings

    def encode_image_patches(
    self,
    images
):

      features = self.vision_encoder(images)

      patches = features[:, 1:]

      patches = self.image_projection(
          patches
      )

      patches = F.normalize(
          patches,
          dim=-1
      )

      return patches

    # --------------------------------------------------------
    # Text Encoder
    # --------------------------------------------------------

    def encode_text(
        self,
        tokens,
        mask=None
    ):

        features = self.text_encoder(tokens)

        if mask is None:

            pooled = features.mean(dim=1)

        else:

            mask = mask.float().unsqueeze(-1)

            pooled = (
                features * mask
            ).sum(dim=1)

            pooled = pooled / mask.sum(
                dim=1
            ).clamp(min=1e-6)

        embeddings = self.text_projection(
            pooled
        )

        embeddings = F.normalize(
            embeddings,
            dim=-1
        )

        return embeddings

    # --------------------------------------------------------
    # Forward
    # --------------------------------------------------------

    def forward(
        self,
        images,
        tokens,
        mask=None
    ):

        image_embeddings = self.encode_image(
            images
        )

        text_embeddings = self.encode_text(
            tokens,
            mask
        )

        loss = self.loss_fn(
            image_embeddings,
            text_embeddings
        )

        return (
            loss,
            image_embeddings,
            text_embeddings
        )

    # --------------------------------------------------------
    # Retrieval utilities
    # --------------------------------------------------------

    @torch.no_grad()
    def image_features(
        self,
        images
    ):

        return self.encode_image(images)

    @torch.no_grad()
    def text_features(
        self,
        tokens,
        mask=None
    ):

        return self.encode_text(
            tokens,
            mask
        )

    @torch.no_grad()
    def similarity(
        self,
        images,
        tokens,
        mask=None
    ):

        img = self.image_features(images)

        txt = self.text_features(
            tokens,
            mask
        )

        return img @ txt.t()

# ============================================================
# Weight Initialization
# ============================================================

def initialize_weights(model):

    """
    Initialize model parameters using Xavier initialization.
    """

    for module in model.modules():

        if isinstance(module, nn.Linear):

            nn.init.xavier_uniform_(module.weight)

            if module.bias is not None:
                nn.init.zeros_(module.bias)

        elif isinstance(module, nn.Conv2d):

            nn.init.kaiming_normal_(
                module.weight,
                mode="fan_out",
                nonlinearity="relu"
            )

            if module.bias is not None:
                nn.init.zeros_(module.bias)

        elif isinstance(module, nn.Embedding):

            nn.init.normal_(
                module.weight,
                mean=0.0,
                std=0.02
            )

        elif isinstance(module, nn.LayerNorm):

            nn.init.ones_(module.weight)
            nn.init.zeros_(module.bias)


# ============================================================
# Parameter Counter
# ============================================================

def count_parameters(model):

    return sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )


# ============================================================
# Quick Test
# ============================================================

if __name__ == "__main__":

    BATCH_SIZE = 4
    IMAGE_SIZE = 64
    MAX_LEN = 32
    VOCAB_SIZE = 10000

    model = CLIPStyleModel(
        vocab_size=VOCAB_SIZE,
        max_length=MAX_LEN,
        embed_dim=192,
        projection_dim=192,
        n_head=6,
        n_layer=6,
    )

    initialize_weights(model)

    print(model)

    print(
        f"\nTrainable Parameters: "
        f"{count_parameters(model):,}"
    )

    images = torch.randn(
        BATCH_SIZE,
        3,
        IMAGE_SIZE,
        IMAGE_SIZE
    )

    tokens = torch.randint(
        0,
        VOCAB_SIZE,
        (
            BATCH_SIZE,
            MAX_LEN
        )
    )

    mask = torch.ones(
        BATCH_SIZE,
        MAX_LEN
    )

    loss, image_embeddings, text_embeddings = model(
        images,
        tokens,
        mask
    )

    print("\nForward Pass Successful!")
    print(f"Loss                : {loss.item():.4f}")
    print(f"Image Embeddings    : {image_embeddings.shape}")
    print(f"Text Embeddings     : {text_embeddings.shape}")

    similarity = model.similarity(
        images,
        tokens,
        mask
    )

    print(f"Similarity Matrix   : {similarity.shape}")