# -*- coding: utf-8 -*-
"""task4/multimodal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yQ1WQThsW90Nvrd6-8UfzqJsR4jP4Dc
"""

import torch
import torch.nn as nn
from torch.nn import functional as F
import matplotlib.pyplot as plt

device = 'cuda' if torch.cuda.is_available() else 'cpu'

class HeadBidirectional(nn.Module):

    def __init__(self, n_embd, head_size, dropout):
        super().__init__()

        self.key = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.query = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.value = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        k = self.key(x)
        q = self.query(x)
        v = self.value(x)

        wei = q @ k.transpose(-2,-1)

        wei = wei * (
            k.size(-1) ** -0.5
        )

        wei = F.softmax(
            wei,
            dim=-1
        )

        wei = self.dropout(wei)

        return wei @ v

class FeedForward(nn.Module):

    def __init__(self,n_embd):
        super().__init__()

        self.net = nn.Sequential(

            nn.Linear(
                n_embd,
                4*n_embd
            ),

            nn.ReLU(),

            nn.Linear(
                4*n_embd,
                n_embd
            ),

            nn.Dropout(0.2)

        )

    def forward(self,x):

        return self.net(x)

class MultiHeadAttentionBidirectional(
    nn.Module
):

    def __init__(
        self,
        n_embd,
        n_head,
        dropout
    ):
        super().__init__()

        head_size = (
            n_embd // n_head
        )

        self.heads = nn.ModuleList([

            HeadBidirectional(
                n_embd,
                head_size,
                dropout
            )

            for _ in range(n_head)

        ])

        self.proj = nn.Linear(
            n_embd,
            n_embd
        )

        self.dropout = nn.Dropout(
            dropout
        )

    def forward(self,x):

        out = torch.cat(
            [h(x) for h in self.heads],
            dim=-1
        )

        out = self.proj(out)

        return self.dropout(out)

class BlockBidirectional(
    nn.Module
):

    def __init__(
        self,
        n_embd,
        n_head,
        dropout
    ):
        super().__init__()

        self.attn = (
            MultiHeadAttentionBidirectional(
                n_embd,
                n_head,
                dropout
            )
        )

        self.ffwd = FeedForward(
            n_embd
        )

        self.ln1 = nn.LayerNorm(
            n_embd
        )

        self.ln2 = nn.LayerNorm(
            n_embd
        )

    def forward(self,x):

        x = x + self.attn(
            self.ln1(x)
        )

        x = x + self.ffwd(
            self.ln2(x)
        )

        return x



class ViTEncoder(nn.Module):

    def __init__(
        self,
        img_size=32,
        patch_size=4,
        in_chans=3,
        n_embd=128,
        n_head=4,
        n_layer=4,
        dropout=0.1
    ):
        super().__init__()

        num_patches = (img_size // patch_size) ** 2

        self.patch_embed = nn.Conv2d(
            in_chans,
            n_embd,
            kernel_size=patch_size,
            stride=patch_size
        )

        self.cls_token = nn.Parameter(
            torch.zeros(1,1,n_embd)
        )

        self.pos_embed = nn.Parameter(
            torch.zeros(
                1,
                num_patches+1,
                n_embd
            )
        )

        self.dropout = nn.Dropout(dropout)

        self.blocks = nn.ModuleList([
            BlockBidirectional(
                n_embd,
                n_head,
                dropout
            )
            for _ in range(n_layer)
        ])

        self.norm = nn.LayerNorm(n_embd)

    def forward(self,x):

        B = x.size(0)

        x = self.patch_embed(x)

        x = x.flatten(2)

        x = x.transpose(1,2)

        cls = self.cls_token.expand(
            B,-1,-1
        )

        x = torch.cat(
            [cls,x],
            dim=1
        )

        x = x + self.pos_embed

        x = self.dropout(x)

        for blk in self.blocks:
            x = blk(x)

        x = self.norm(x)

        return x

class CrossAttentionHead(nn.Module):

    def __init__(self,n_embd,head_size):

        super().__init__()

        self.key = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.query = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.value = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )
        self.last_attn = None

    def forward(self,x,context):

        q = self.query(x)

        k = self.key(context)

        v = self.value(context)

        wei = q @ k.transpose(-2,-1)

        wei = wei * (
            k.size(-1) ** -0.5
        )

        wei = F.softmax(
            wei,
            dim=-1
        )

        out = wei @ v
        self.last_attn = wei.detach()

        return out
class MultiHeadCrossAttention(nn.Module):

    def __init__(
        self,
        n_embd,
        n_head
    ):
        super().__init__()

        head_size = n_embd // n_head

        self.heads = nn.ModuleList([

            CrossAttentionHead(
                n_embd,
                head_size
            )

            for _ in range(n_head)

        ])

        self.proj = nn.Linear(
            n_embd,
            n_embd
        )

    def forward(
        self,
        x,
        context
    ):

        out = torch.cat(
            [
                h(x,context)
                for h in self.heads
            ],
            dim=-1
        )

        return self.proj(out)

class Head(nn.Module):

    def __init__(
        self,
        n_embd,
        head_size,
        block_size
    ):
        super().__init__()

        self.key = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.query = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.value = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.register_buffer(
            "tril",
            torch.tril(
                torch.ones(
                    block_size,
                    block_size
                )
            )
        )

        self.dropout = nn.Dropout(
            0.2
        )

    def forward(self,x):

        B,T,C = x.shape

        k = self.key(x)

        q = self.query(x)

        v = self.value(x)

        wei = q @ k.transpose(-2,-1)

        wei = wei * (
            k.size(-1) ** -0.5
        )

        wei = wei.masked_fill(
            self.tril[:T,:T] == 0,
            float("-inf")
        )

        wei = F.softmax(
            wei,
            dim=-1
        )

        wei = self.dropout(wei)

        out = wei @ v

        return out

class MultiHeadAttention(nn.Module):

    def __init__(
        self,
        n_embd,
        n_head,
        head_size,
        block_size
    ):
        super().__init__()

        self.heads = nn.ModuleList([

            Head(
                n_embd,
                head_size,
                block_size
            )

            for _ in range(n_head)

        ])

        self.proj = nn.Linear(
            n_embd,
            n_embd
        )

        self.dropout = nn.Dropout(
            0.2
        )

    def forward(self,x):

        out = torch.cat(
            [h(x) for h in self.heads],
            dim=-1
        )

        out = self.proj(out)

        out = self.dropout(out)

        return out



class DecoderBlock(nn.Module):

    def __init__(
        self,
        n_embd,
        n_head,
        block_size
    ):
        super().__init__()

        head_size = (
            n_embd // n_head
        )

        self.self_attn = MultiHeadAttention(
            n_embd,
            n_head,
            head_size,
            block_size
        )

        self.cross_attn = (
            MultiHeadCrossAttention(
                n_embd,
                n_head
            )
        )

        self.ffwd = FeedForward(
            n_embd
        )

        self.ln1 = nn.LayerNorm(
            n_embd
        )

        self.ln2 = nn.LayerNorm(
            n_embd
        )

        self.ln3 = nn.LayerNorm(
            n_embd
        )

    def forward(
        self,
        x,
        image_features
    ):

        x = x + self.self_attn(
            self.ln1(x)
        )

        x = x + self.cross_attn(
            self.ln2(x),
            image_features
        )

        x = x + self.ffwd(
            self.ln3(x)
        )

        return x

class MultimodalModel(nn.Module):

    def __init__(
        self,
        vocab_size,
        n_embd=128,
        n_head=4,
        n_layer=4,
        block_size=64
    ):
        super().__init__()

        self.vision_encoder = (
            ViTEncoder(
                n_embd=n_embd,
                n_head=n_head,
                n_layer=n_layer
            )
        )

        self.token_embed = (
            nn.Embedding(
                vocab_size,
                n_embd
            )
        )

        self.pos_embed = (
            nn.Embedding(
                block_size,
                n_embd
            )
        )

        self.blocks = nn.ModuleList([

            DecoderBlock(
                n_embd,
                n_head,
                block_size
            )

            for _ in range(n_layer)

        ])

        self.ln_f = nn.LayerNorm(
            n_embd
        )

        self.lm_head = nn.Linear(
            n_embd,
            vocab_size
        )

    def forward(
        self,
        image,
        text_ids,
        targets=None
    ):

        image_feats = (
            self.vision_encoder(
                image
            )
        )

        B,T = text_ids.shape

        tok = self.token_embed(
            text_ids
        )

        pos = self.pos_embed(

            torch.arange(
                T,
                device=text_ids.device
            )

        )

        x = tok + pos

        for blk in self.blocks:

            x = blk(
                x,
                image_feats
            )

        x = self.ln_f(x)

        logits = self.lm_head(x)

        loss = None

        if targets is not None:

            loss = F.cross_entropy(

                logits.view(
                    -1,
                    logits.size(-1)
                ),

                targets.view(-1)

            )

        return logits, loss

    def generate(
      self,
      image,
      start_ids,
      max_new_tokens=20
):

      idx = start_ids

      for _ in range(max_new_tokens):

          logits, _ = self(
              image,
              idx
          )

          logits = logits[:, -1, :]

          probs = F.softmax(
              logits,
              dim=-1
          )

          next_token = torch.multinomial(
              probs,
              num_samples=1
          )

          idx = torch.cat(
              [idx, next_token],
              dim=1
          )

      return idx

cifar_classes = [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck"
]


all_text = ""

for cls in cifar_classes:

    all_text += (
        "this is a "
        + cls
    )




from torch.utils.data import Dataset

class CIFARCaptionDataset(Dataset):

    def __init__(
        self,
        cifar_dataset,
        stoi,
        block_size=32
    ):
        self.dataset = cifar_dataset
        self.stoi = stoi
        self.block_size = block_size

        self.class_names = [
            "airplane",
            "automobile",
            "bird",
            "cat",
            "deer",
            "dog",
            "frog",
            "horse",
            "ship",
            "truck"
        ]

    def encode(self, text):
        return [self.stoi[c] for c in text]

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):

        image, label = self.dataset[idx]

        # Example:
        # label=3 -> "this is a cat"
        caption = (
            "this is a "
            + self.class_names[label]
        )

        ids = self.encode(caption)

        # GPT-style next token prediction
        x = ids[:-1]
        y = ids[1:]

        # truncate
        x = x[:self.block_size]
        y = y[:self.block_size]

        # pad
        while len(x) < self.block_size:
            x.append(0)

        while len(y) < self.block_size:
            y.append(0)

        return (
            image,
            torch.tensor(x, dtype=torch.long),
            torch.tensor(y, dtype=torch.long)
        )

captions = []

for cls in cifar_classes:

    captions.append(
        "this is a " + cls
    )

all_text = "".join(captions)

chars = sorted(
    list(
        set(all_text)
    )
)

stoi = {
    ch:i
    for i,ch in enumerate(chars)
}

itos = {
    i:ch
    for i,ch in enumerate(chars)
}

vocab_size = len(chars)

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.ToTensor()

train_dataset = datasets.CIFAR10(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.CIFAR10(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_caption_dataset = (
    CIFARCaptionDataset(
        train_dataset,
        stoi
    )
)

test_caption_dataset = (
    CIFARCaptionDataset(
        test_dataset,
        stoi
    )
)

train_loader = DataLoader(
    train_caption_dataset,
    batch_size=128,
    shuffle=True
)

test_loader = DataLoader(
    test_caption_dataset,
    batch_size=128,
    shuffle=False
)

model = MultimodalModel(
    vocab_size=vocab_size,
    n_embd=128,
    n_head=4,
    n_layer=4,
    block_size=32
).to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=3e-4
)

num_epochs = 10

losses = []

for epoch in range(num_epochs):

    model.train()

    running_loss = 0

    for images,x,y in train_loader:

        images = images.to(device)

        x = x.to(device)

        y = y.to(device)

        logits,loss = model(
            images,
            x,
            y
        )

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    avg_loss = (
        running_loss /
        len(train_loader)
    )

    losses.append(avg_loss)

    print(
        f"Epoch {epoch+1}: "
        f"Loss = {avg_loss:.4f}"
    )

plt.figure(figsize=(8,5))

plt.plot(losses)

plt.xlabel("Epoch")

plt.ylabel("Loss")

plt.title(
    "Multimodal Training Loss"
)

plt.savefig(
    "training_curve.png"
)

plt.show()


def decode(tokens):

    return "".join(
        [
            itos[i]
            for i in tokens
        ]
    )
samples = []

model.eval()

with torch.no_grad():

    for i in range(10):

        image,_,_ = (
            test_caption_dataset[i]
        )

        image = (
            image
            .unsqueeze(0)
            .to(device)
        )

        start = torch.tensor(
            [[stoi["t"]]],
            device=device
        )

        out = model.generate(
            image,
            start,
            max_new_tokens=20
        )

        text = decode(
            out[0].cpu().tolist()
        )

        print(text)

        samples.append(text)
with open(
    "samples.txt",
    "w"
) as f:

    for s in samples:

        f.write(s + "\n")

# ==========================
# PART D: ATTENTION VISUALIZATION
# ==========================

print("\nGenerating attention visualization...")

model.eval()

image, _, _ = test_caption_dataset[0]

image = image.unsqueeze(0).to(device)

start = torch.tensor(
    [[stoi["t"]]],
    device=device
)

generated = model.generate(
    image,
    start,
    max_new_tokens=15
)

caption = decode(
    generated[0].cpu().tolist()
)

print("Generated caption:")
print(caption)

# run one forward pass so attention gets stored

with torch.no_grad():

    logits, _ = model(
        image,
        generated
    )

# grab attention from:
# last decoder block
# first cross-attention head

attn = (
    model.blocks[-1]
    .cross_attn
    .heads[0]
    .last_attn
)

print("Attention shape:", attn.shape)

# remove batch dimension

attn = attn[0].cpu()

# remove CLS token

attn = attn[:, 1:]

print("Heatmap shape:", attn.shape)

plt.figure(figsize=(10,6))

plt.imshow(
    attn,
    aspect="auto"
)

plt.xlabel("Image Patch Index")
plt.ylabel("Generated Character Position")

plt.title(
    "Cross Attention Heatmap"
)

plt.colorbar()

plt.tight_layout()

plt.savefig(
    "attention_viz.png"
)

plt.show()