# -*- coding: utf-8 -*-
"""task3/vit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vnbMg2Xoi-YT8mz0cGeKC4yobdll5zq
"""

import torch
import torch.nn as nn

# Dummy CIFAR batch
x = torch.randn(2, 3, 32, 32)

print("Input shape:", x.shape)

patch_size = 4

# Extract non-overlapping patches
patches = x.unfold(2, patch_size, patch_size) \
           .unfold(3, patch_size, patch_size)

print("After unfold:", patches.shape)

patches = patches.permute(
    0,  # batch
    2,  # patch rows
    3,  # patch cols
    1,  # channels
    4,  # patch height
    5   # patch width
)

print("After permute:", patches.shape)

patches = patches.flatten(1, 2)

print("After flatten(1,2):", patches.shape)

patches = patches.flatten(2)

print("Final patch shape:", patches.shape)

n_embd = 128

linear_proj = nn.Linear(48, n_embd)

patch_embeddings_manual = linear_proj(patches)

print(patch_embeddings_manual.shape)

#method 2

patch_embed = nn.Conv2d(
    in_channels=3,
    out_channels=n_embd,
    kernel_size=patch_size,
    stride=patch_size
)

conv_out = patch_embed(x)

print(conv_out.shape)

conv_out = conv_out.flatten(2)

print(conv_out.shape)

patch_embeddings_conv = conv_out.transpose(1, 2)

print(patch_embeddings_conv.shape)

print("Manual:", patch_embeddings_manual.shape)
print("Conv2D:", patch_embeddings_conv.shape)

class PatchEmbedding(nn.Module):

    def __init__(self, img_size=32, patch_size=4, n_embd=128):
        super().__init__()

        self.patch_embed = nn.Conv2d(
            in_channels=3,
            out_channels=n_embd,
            kernel_size=patch_size,
            stride=patch_size
        )

        num_patches = (img_size // patch_size) ** 2

        # CLS token
        self.cls_token = nn.Parameter(
            torch.zeros(1, 1, n_embd)
        )

        # Position embeddings
        self.pos_embed = nn.Parameter(
            torch.zeros(1, num_patches + 1, n_embd)
        )

        nn.init.trunc_normal_(
            self.pos_embed,
            std=0.02
        )

        nn.init.trunc_normal_(
            self.cls_token,
            std=0.02
        )

    def forward(self, x):

      B = x.shape[0]

      # ---------------------------------
      # Patch embedding
      # (B,3,32,32)
      # ->
      # (B,n_embd,8,8)
      # ---------------------------------

      x = self.patch_embed(x)

      # ---------------------------------
      # (B,n_embd,8,8)
      # ->
      # (B,n_embd,64)
      # ---------------------------------

      x = x.flatten(2)

      # ---------------------------------
      # (B,n_embd,64)
      # ->
      # (B,64,n_embd)
      # ---------------------------------

      x = x.transpose(1, 2)

      # ---------------------------------
      # CLS token
      # ---------------------------------

      cls_tokens = self.cls_token.expand(
          B,
          -1,
          -1
      )

      # ---------------------------------
      # prepend CLS token
      # (B,64,n_embd)
      # ->
      # (B,65,n_embd)
      # ---------------------------------

      x = torch.cat(
          (cls_tokens, x),
          dim=1
      )

      # ---------------------------------
      # add positional embeddings
      # ---------------------------------

      x = x + self.pos_embed

      return x

import torch
import torch.nn as nn
import torch.nn.functional as F

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

device = 'cuda' if torch.cuda.is_available() else 'cpu'

transform = transforms.ToTensor()

train_dataset = datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.CIFAR10(
    root='./data',
    train=False,
    download=True,
    transform=transform
)
batch_size = 128

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False
)
class HeadBidirectional(nn.Module):

    def __init__(self, n_embd, head_size, dropout):

        super().__init__()

        self.key = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.query = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.value = nn.Linear(
            n_embd,
            head_size,
            bias=False
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        B, T, C = x.shape

        k = self.key(x)

        q = self.query(x)

        v = self.value(x)

        wei = q @ k.transpose(-2, -1)

        wei = wei * (k.size(-1) ** -0.5)

        # NO MASK

        wei = F.softmax(
            wei,
            dim=-1
        )

        wei = self.dropout(wei)

        out = wei @ v

        return out

class FeedForward(nn.Module):

    def __init__(self, n_embd, dropout):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout)
        )

    def forward(self, x):
        return self.net(x)

class MultiHeadAttentionBidirectional(nn.Module):

    def __init__(self, n_embd, n_head, dropout):
        super().__init__()

        head_size = n_embd // n_head

        self.heads = nn.ModuleList([
            HeadBidirectional(
                n_embd,
                head_size,
                dropout
            )
            for _ in range(n_head)
        ])

        self.proj = nn.Linear(
            n_embd,
            n_embd
        )

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        out = torch.cat(
            [h(x) for h in self.heads],
            dim=-1
        )

        out = self.dropout(
            self.proj(out)
        )

        return out

class BlockBidirectional(nn.Module):

    def __init__(self, n_embd, n_head, dropout):
        super().__init__()

        self.attn = MultiHeadAttentionBidirectional(
            n_embd,
            n_head,
            dropout
        )

        self.ffwd = FeedForward(
            n_embd,
            dropout
        )

        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):

        x = x + self.attn(
            self.ln1(x)
        )

        x = x + self.ffwd(
            self.ln2(x)
        )

        return x


class ViT(nn.Module):

    def __init__(
        self,
        img_size=32,
        patch_size=4,
        in_chans=3,
        num_classes=10,
        n_embd=192,
        n_head=6,
        n_layer=6,
        dropout=0.1
    ):

        super().__init__()

        num_patches = (
            img_size // patch_size
        ) ** 2

        self.patch_embed = nn.Conv2d(
            in_chans,
            n_embd,
            kernel_size=patch_size,
            stride=patch_size
        )

        self.cls_token = nn.Parameter(
            torch.zeros(
                1,
                1,
                n_embd
            )
        )

        self.pos_embed = nn.Parameter(
            torch.zeros(
                1,
                num_patches + 1,
                n_embd
            )
        )

        self.dropout = nn.Dropout(
            dropout
        )

        self.blocks = nn.ModuleList([
            BlockBidirectional(
                n_embd,
                n_head,
                dropout
            )
            for _ in range(n_layer)
        ])

        self.norm = nn.LayerNorm(
            n_embd
        )

        self.head = nn.Linear(
            n_embd,
            num_classes
        )

        nn.init.trunc_normal_(
            self.cls_token,
            std=0.02
        )

        nn.init.trunc_normal_(
            self.pos_embed,
            std=0.02
        )

    def forward(self, x):

        B = x.size(0)

        x = self.patch_embed(x)

        x = x.flatten(2)

        x = x.transpose(1, 2)

        cls = self.cls_token.expand(
            B,
            -1,
            -1
        )

        x = torch.cat(
            [cls, x],
            dim=1
        )

        x = x + self.pos_embed

        x = self.dropout(x)

        for blk in self.blocks:
            x = blk(x)

        x = self.norm(x)

        cls_final = x[:, 0]

        logits = self.head(cls_final)

        return logits

model = ViT(
    img_size=32,
    patch_size=4,
    in_chans=3,
    num_classes=10,
    n_embd=192,
    n_head=6,
    n_layer=6,
    dropout=0.1
).to(device)

x, y = next(iter(train_loader))

x = x.to(device)

out = model(x)

print("Input shape :", x.shape)
print("Output shape:", out.shape)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=3e-4
)

train_losses = []

train_accs = []

val_accs = []

num_epochs = 30

for epoch in range(num_epochs):

    # ==========================
    # Training
    # ==========================

    model.train()

    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for x, y in train_loader:

        x = x.to(device)
        y = y.to(device)

        outputs = model(x)

        loss = criterion(
            outputs,
            y
        )

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        train_loss += loss.item()

        _, predicted = outputs.max(1)

        train_total += y.size(0)

        train_correct += (
            predicted == y
        ).sum().item()

    train_acc = (
        100 * train_correct / train_total
    )

    avg_train_loss = (
        train_loss / len(train_loader)
    )

    # ==========================
    # Validation
    # ==========================

    model.eval()

    val_correct = 0
    val_total = 0

    with torch.no_grad():

        for x, y in test_loader:

            x = x.to(device)
            y = y.to(device)

            outputs = model(x)

            _, predicted = outputs.max(1)

            val_total += y.size(0)

            val_correct += (
                predicted == y
            ).sum().item()

    val_acc = (
        100 * val_correct / val_total
    )

    train_losses.append(
        avg_train_loss
    )

    train_accs.append(
        train_acc
    )

    val_accs.append(
        val_acc
    )

    print(
        f"Epoch [{epoch+1}/{num_epochs}] "
        f"Loss: {avg_train_loss:.4f} "
        f"Train Acc: {train_acc:.2f}% "
        f"Val Acc: {val_acc:.2f}%"
    )

import matplotlib.pyplot as plt

epochs = range(1, num_epochs + 1)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)

plt.plot(
    epochs,
    train_losses,
    marker='o',
    label='Train Loss'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("ViT Training Loss")
plt.legend()

plt.subplot(1,2,2)

plt.plot(
    epochs,
    train_accs,
    marker='o',
    label='Train Accuracy'
)

plt.plot(
    epochs,
    val_accs,
    marker='o',
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("ViT Accuracy")
plt.legend()

plt.tight_layout()

plt.savefig(
    "vit_training_curves.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

torch.save(
    model.state_dict(),
    "vit_cifar10.pth"
)

print("Model saved successfully.")

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

cnn_epochs = list(range(1, 11))
cnn_train = [41.36,56.56,63.75,67.87,71.82,74.11,76.34,78.18,79.86,81.40]
cnn_val = [52.08,61.88,67.42,70.11,72.00,71.49,74.09,74.15,75.46,74.99]

vit_epochs = list(range(1, 31))
vit_train = [29.23,46.54,52.77,55.89,58.38,60.20,61.70,62.88,64.12,65.45,66.25,67.70,68.42,69.50,70.94,71.87,72.70,73.94,74.89,76.12,77.19,78.18,79.18,80.28,81.39,82.38,83.17,84.34,85.41,85.95]
vit_val = [42.03,51.88,56.04,57.07,58.27,59.95,59.42,61.40,62.01,61.70,63.22,62.73,63.73,63.79,64.25,64.57,64.41,65.29,65.45,64.66,64.20,65.47,65.70,65.14,65.36,65.74,65.74,65.49,63.91,64.35]

plt.figure(figsize=(8,5))
plt.plot(cnn_epochs, cnn_val, marker='o', label='CNN Validation')
plt.plot(vit_epochs, vit_val, marker='o', label='ViT Validation')
plt.ylim(0,100)
plt.xlim(1,30)
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy (%)")
plt.title("CNN vs ViT Validation Accuracy on CIFAR-10")
plt.legend()
plt.tight_layout()
plt.show()