# -*- coding: utf-8 -*-
"""task1/bigram.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyfrEWQZSCJcGE2WdQP-thQkrxHqetVY
"""

from google.colab import files

uploaded = files.upload()

import torch
import torch.nn as nn
from torch.nn import functional as F

#hyperparameters
batch_size = 32
block_size = 8
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

with open('task1_input.txt', 'r', encoding='utf-8') as f:
    text = f.read() #read the text

chars = sorted(list(set(text))) #set gives unique chars, sorted sorts the list in alphabetical order
vocab_size = len(chars)

#tokenizer
stoi = { ch:i for i,ch in enumerate(chars) } #numerical mapping from str to int
itos = { i:ch for i,ch in enumerate(chars) } #reverse mapping

#encode/decode the text
encode = lambda s:[stoi[c] for c in s]
decode = lambda l:''.join([itos[i] for i in l])

#encode the entire dataset
data = torch.tensor(encode(text),dtype = torch.long)

#train/test split
n = int(0.9 * len(data))
train_data = data[:n] #first 900 elements
val_data = data[n:] #last 100 elements

def get_batch(split):
  data = train_data if split == 'train' else val_data
  ix = torch.randint(len(data)-block_size , (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x,y = x.to(device),y.to(device)
  return x,y

#BIGRAM MODEL
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) #table has a shape of vocab_size x vocab_size

    def forward(self,idx,targets=None):
      logits = self.token_embedding_table(idx) #unnormalized scores

      #Loss Calculation
      if targets is None:
        loss = None
      else:
        B,T,C = logits.shape
        logits = logits.view(B*T,C) #flattening the logits
        targets = targets.view(B*T)
        loss = F.cross_entropy(logits,targets) #cross entropy loss
      return logits,loss

    def generate(self,idx,max_new_tokens):
      for _ in range(max_new_tokens):
        logits, loss = self(idx) #call the model onto idx
        logits = logits[:,-1,:] #last character
        probs = F.softmax(logits,dim=-1) #converst logits into probabiltites
        idx_next = torch.multinomial(probs,num_samples=1) #predicts the next character based on the probabilities
        idx = torch.cat((idx,idx_next),dim=1) #append the tokens
      return idx

model = BigramLanguageModel().to(device)
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

  #Training loop
for iter in range(max_iters):
  xb,yb = get_batch('train')
  logits,loss = model(xb,yb)
  optimizer.zero_grad(set_to_none = True)
  loss.backward() #backpropogation
  optimizer.step() #changes the weights to optimize the model

  if iter%300 == 0:
    print(loss.item()) #print the loss after every 300 iterations

context = torch.zeros((1,1),dtype = torch.long, device = device)
print(decode(model.generate(context, max_new_tokens=500)[0].tolist())) #generate the encdoings and decode for us to see
