# -*- coding: utf-8 -*-
"""task6/qualitative

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OArgV8hkzQLvZ25SD3OwrpJykSwZldgs
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import numpy as np

from tqdm import tqdm
from torch.utils.data import DataLoader, random_split

from task5_clip_model import CLIPStyleModel
from task6_dataset import (
    Flickr8kDataset,
    tokenizer,
    captions,
    image_dir,
    denormalize_image,
)

# ============================================================
# Device
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(f"Using {device}")

# ============================================================
# Dataset
# ============================================================

dataset = Flickr8kDataset(

    dataframe=captions,

    image_dir=image_dir,

    tokenizer=tokenizer,

    image_size=64,

    max_length=32,

    train=False

)

train_size = int(0.8 * len(dataset))
val_size = int(0.1 * len(dataset))
test_size = len(dataset) - train_size - val_size

generator = torch.Generator().manual_seed(42)

_, val_dataset, _ = random_split(

    dataset,

    [train_size, val_size, test_size],

    generator=generator

)

val_loader = DataLoader(

    val_dataset,

    batch_size=1,

    shuffle=False

)

# ============================================================
# Model
# ============================================================

model = CLIPStyleModel(

    vocab_size=len(tokenizer.word2idx),

    embed_dim=192,

    projection_dim=128,

    n_head=6,

    n_layer=4,

    max_length=32,

    dropout=0.1

).to(device)

model.load_state_dict(

    torch.load(

        "/content/drive/MyDrive/SoC_Task6/best_model.pt",

        map_location=device

    )

)

model.eval()

print("Model loaded.")

# ============================================================
# Patch-Caption Similarity
# ============================================================

@torch.no_grad()

def compute_similarity_map(

    image,

    tokens,

    mask

):

    patches = model.encode_image_patches(

        image

    )[0]                 # (64,D)

    text = model.encode_text(

        tokens,

        mask

    )[0]                 # (D)

    similarity = (

        patches @ text

    )

    similarity = similarity.reshape(

        8,

        8

    )

    similarity -= similarity.min()

    similarity /= (

        similarity.max()

        + 1e-8

    )

    return similarity.cpu().numpy()

# ============================================================
# Heatmap Overlay
# ============================================================

def create_overlay(

    image_tensor,

    similarity_map

):

    image = denormalize_image(

        image_tensor.cpu()

    )

    heatmap = torch.tensor(

        similarity_map,

        dtype=torch.float32

    ).unsqueeze(0).unsqueeze(0)

    heatmap = F.interpolate(

        heatmap,

        size=(64,64),

        mode="bilinear",

        align_corners=False

    )

    heatmap = heatmap.squeeze().numpy()

    return image, heatmap

# ============================================================
# Evaluate Entire Validation Set
# ============================================================

results = []

print("Scoring validation examples...")

with torch.no_grad():

    for batch in tqdm(val_loader):

        image = batch["image"].to(device)

        tokens = batch["tokens"].to(device)

        mask = batch["mask"].to(device)

        caption = batch["caption"][0]

        image_name = batch["image_name"][0]

        image_embedding = model.encode_image(

            image

        )

        text_embedding = model.encode_text(

            tokens,

            mask

        )

        score = (

            image_embedding

            @

            text_embedding.T

        ).item()

        similarity_map = compute_similarity_map(

            image,

            tokens,

            mask

        )

        image_np, heatmap = create_overlay(

            image[0],

            similarity_map

        )

        results.append(

            {

                "score": score,

                "image": image_np,

                "heatmap": heatmap,

                "caption": caption,

                "image_name": image_name

            }

        )

# ============================================================
# Sort Examples
# ============================================================

results = sorted(

    results,

    key=lambda x: x["score"],

    reverse=True

)

best_examples = results[:5]

failure_examples = results[-2:]

examples = best_examples + failure_examples

print(

    f"Selected {len(best_examples)} good examples "

    f"and {len(failure_examples)} failure cases."

)

# ============================================================
# Plot
# ============================================================

fig, axes = plt.subplots(

    len(examples),

    2,

    figsize=(10, 4 * len(examples))

)

if len(examples) == 1:

    axes = np.expand_dims(

        axes,

        axis=0

    )

for row, sample in enumerate(examples):

    axes[row, 0].imshow(

        sample["image"]

    )

    axes[row, 0].set_title(

        sample["image_name"],

        fontsize=10

    )

    axes[row, 0].axis("off")

    axes[row, 1].imshow(

        sample["image"]

    )

    axes[row, 1].imshow(

        sample["heatmap"],

        cmap="jet",

        alpha=0.45

    )

    axes[row, 1].set_title(

        f"{sample['score']:.3f}\n"

        f"{sample['caption']}",

        fontsize=9

    )

    axes[row, 1].axis("off")

# ============================================================
# Save Figure
# ============================================================

plt.tight_layout()

plt.savefig(

    "/content/drive/MyDrive/SoC_Task6/qualitative.png",

    dpi=300,

    bbox_inches="tight"

)

plt.show()

print("\nSaved qualitative visualization.")

# ============================================================
# Summary
# ============================================================

print("\n" + "=" * 60)
print("Qualitative Evaluation Summary")
print("=" * 60)

print(
    f"Validation Examples : {len(results)}"
)

print(
    f"Best Similarity     : {best_examples[0]['score']:.4f}"
)

print(
    f"Worst Similarity    : {failure_examples[0]['score']:.4f}"
)

print("\nTop-5 Examples")

for i, sample in enumerate(best_examples):

    print(

        f"{i+1}. "

        f"{sample['image_name']} "

        f"({sample['score']:.4f})"

    )

print("\nFailure Cases")

for i, sample in enumerate(failure_examples):

    print(

        f"{i+1}. "

        f"{sample['image_name']} "

        f"({sample['score']:.4f})"

    )

print("\nFigure saved to:")

print(

    "/content/drive/MyDrive/SoC_Task6/qualitative.png"

)

print("\nDone.")