# -*- coding: utf-8 -*-
"""task6/text_to_image_search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hdLD4lu_lSts2wOXRKqUJznibbnv5-F
"""

import os
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output
from PIL import Image
from torch.utils.data import DataLoader

from task5_clip_model import CLIPStyleModel
from task6_dataset import (
    Flickr8kDataset,
    tokenizer,
    captions,
    image_dir
)

# ============================================================
# Device
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Using", device)

# ============================================================
# Keep only unique Flickr8k images
# ============================================================

image_column = captions.columns[0]

unique_images = captions.drop_duplicates(

    subset=image_column

).reset_index(drop=True)

print(

    f"Unique images : {len(unique_images)}"

)

dataset = Flickr8kDataset(

    dataframe=unique_images,

    image_dir=image_dir,

    tokenizer=tokenizer,

    image_size=64,

    max_length=32,

    train=False

)

loader = DataLoader(

    dataset,

    batch_size=64,

    shuffle=False

)

# ============================================================
# Load Model
# ============================================================

model = CLIPStyleModel(

    vocab_size=len(tokenizer.word2idx),

    embed_dim=192,

    projection_dim=128,

    n_head=6,

    n_layer=4,

    max_length=32,

    dropout=0.1

).to(device)

model.load_state_dict(

    torch.load(

        "/content/drive/MyDrive/SoC_Task6/best_model.pt",

        map_location=device

    )

)

model.eval()

print("Model loaded.")

# ============================================================
# Encode Text Query
# ============================================================

@torch.no_grad()
def encode_query(query):

    tokens = tokenizer.encode(query)

    if len(tokens) > 32:

        tokens = tokens[:32]

        tokens[-1] = tokenizer.word2idx["<EOS>"]

    mask = [1] * len(tokens)

    while len(tokens) < 32:

        tokens.append(
            tokenizer.word2idx["<PAD>"]
        )
        mask.append(0)

    tokens = torch.tensor(
        tokens,
        dtype=torch.long
    ).unsqueeze(0).to(device)

    mask = torch.tensor(
        mask,
        dtype=torch.long
    ).unsqueeze(0).to(device)

    embedding = model.encode_text(
        tokens,
        mask
    )

    embedding = F.normalize(
        embedding,
        dim=-1
    )

    return embedding


# ============================================================
# Build Image Embedding Database
# ============================================================

print("\nEncoding all Flickr8k images...")

image_embeddings = []
image_files = []

with torch.no_grad():

    for batch in loader:

        images = batch["image"].to(device)

        embeddings = model.encode_image(
            images
        )

        embeddings = F.normalize(
            embeddings,
            dim=-1
        )

        image_embeddings.append(
            embeddings.cpu()
        )

        image_files.extend(
            batch["image_name"]
        )

image_embeddings = torch.cat(
    image_embeddings,
    dim=0
)

print(
    f"Indexed {len(image_files)} unique images."
)


# ============================================================
# Search Function
# ============================================================

@torch.no_grad()
def search(query, top_k=5):

    query_embedding = encode_query(
        query
    ).cpu()

    similarity = (
        query_embedding
        @
        image_embeddings.T
    ).squeeze(0)

    scores, indices = torch.topk(
        similarity,
        k=top_k
    )

    results = []

    for idx, score in zip(indices, scores):

        results.append(

            {

                "image_name": image_files[idx],

                "score": score.item()

            }

        )

    return results

# ============================================================
# Interactive Search
# ============================================================

print("\nSemantic Image Search Engine")
print("Type 'quit' to exit.")

# ============================================================
# Interactive Search Widget
# ============================================================

query_box = widgets.Text(

    value="",

    placeholder="Enter a search query...",

    description="Search:",

    layout=widgets.Layout(width="60%")

)

search_button = widgets.Button(

    description="Search",

    button_style="primary"

)

output = widgets.Output()

display(

    widgets.HBox(

        [

            query_box,

            search_button

        ]

    )

)

display(output)

def run_search(_):

    with output:

        clear_output(wait=True)

        query = query_box.value.strip()

        if len(query) == 0:

            print("Enter a query.")

            return

        results = search(

            query,

            top_k=5

        )

        print(f"\nQuery : {query}\n")

        fig, axes = plt.subplots(

            1,

            5,

            figsize=(18,4)

        )

        for ax, result in zip(

            axes,

            results

        ):

            image = Image.open(

                os.path.join(

                    image_dir,

                    result["image_name"]

                )

            ).convert("RGB")

            ax.imshow(image)

            ax.set_title(

                f"{result['score']:.3f}",

                fontsize=10

            )

            ax.axis("off")

        plt.tight_layout()

        plt.show()


search_button.on_click(run_search)