# -*- coding: utf-8 -*-
"""task6/zero_shot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ezOHfE5kQV7a-3vPG9M4HrGswdwvO3H
"""

import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

from torch.utils.data import DataLoader, random_split

from task5_clip_model import CLIPStyleModel
from task6_dataset import (
    Flickr8kDataset,
    tokenizer,
    captions,
    image_dir,
    denormalize_image
)

# ============================================================
# Device
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(f"Using {device}")

# ============================================================
# Dataset
# ============================================================

dataset = Flickr8kDataset(

    dataframe=captions,

    image_dir=image_dir,

    tokenizer=tokenizer,

    image_size=64,

    max_length=32,

    train=False

)

train_size = int(0.8 * len(dataset))
val_size = int(0.1 * len(dataset))
test_size = len(dataset) - train_size - val_size

generator = torch.Generator().manual_seed(42)

_, val_dataset, _ = random_split(

    dataset,

    [train_size, val_size, test_size],

    generator=generator

)

val_loader = DataLoader(

    val_dataset,

    batch_size=1,

    shuffle=True

)

# ============================================================
# Model
# ============================================================

model = CLIPStyleModel(

    vocab_size=len(tokenizer.word2idx),

    embed_dim=192,

    projection_dim=128,

    n_head=6,

    n_layer=4,

    max_length=32,

    dropout=0.1

).to(device)

model.load_state_dict(

    torch.load(

        "/content/drive/MyDrive/SoC_Task6/best_model.pt",

        map_location=device

    )

)

model.eval()

print("Model loaded.")

# ============================================================
# Zero-shot Classes
# ============================================================

class_prompts = [

    "a photo of a person",

    "a photo of a dog",

    "a photo of a horse",

    "a photo of a bicycle",

    "a photo of a car",

    "a photo of a bird",

    "a photo of a child",

    "a photo of people"

]

# ============================================================
# Encode Class Prompts
# ============================================================

@torch.no_grad()
def encode_prompt(prompt):

    tokens = tokenizer.encode(prompt)

    if len(tokens) > 32:

        tokens = tokens[:32]

        tokens[-1] = tokenizer.word2idx["<EOS>"]

    mask = [1] * len(tokens)

    while len(tokens) < 32:

        tokens.append(
            tokenizer.word2idx["<PAD>"]
        )

        mask.append(0)

    tokens = torch.tensor(
        tokens,
        dtype=torch.long
    ).unsqueeze(0).to(device)

    mask = torch.tensor(
        mask,
        dtype=torch.long
    ).unsqueeze(0).to(device)

    embedding = model.encode_text(
        tokens,
        mask
    )

    embedding = F.normalize(
        embedding,
        dim=-1
    )

    return embedding


# ------------------------------------------------------------

print("Encoding class prompts...")

text_embeddings = []

for prompt in class_prompts:

    embedding = encode_prompt(prompt)

    text_embeddings.append(
        embedding
    )

text_embeddings = torch.cat(
    text_embeddings,
    dim=0
)

print("Done.")

# ============================================================
# Zero-Shot Prediction
# ============================================================

NUM_IMAGES = 10

predictions = []

with torch.no_grad():

    for i, batch in enumerate(val_loader):

        if i == NUM_IMAGES:
            break

        image = batch["image"].to(device)

        caption = batch["caption"][0]

        image_embedding = model.encode_image(
            image
        )

        image_embedding = F.normalize(
            image_embedding,
            dim=-1
        )

        similarity = (

            image_embedding

            @

            text_embeddings.T

        ).squeeze(0)

        prediction = torch.argmax(
            similarity
        ).item()

        confidence = similarity[
            prediction
        ].item()

        predictions.append(

            {

                "image": denormalize_image(
                    batch["image"][0]
                ),

                "caption": caption,

                "prediction": class_prompts[
                    prediction
                ],

                "confidence": confidence

            }

        )

# ============================================================
# Display Predictions
# ============================================================

fig, axes = plt.subplots(

    2,

    5,

    figsize=(18, 8)

)

axes = axes.flatten()

correct = 0

print("\n" + "=" * 70)
print("Zero-Shot Classification Results")
print("=" * 70)

for i, sample in enumerate(predictions):

    axes[i].imshow(

        sample["image"]

    )

    predicted = sample["prediction"].replace(

        "a photo of a ",

        ""

    ).replace(

        "a photo of ",

        ""

    )

    axes[i].set_title(

        f"Pred: {predicted}\n"

        f"Score: {sample['confidence']:.2f}",

        fontsize=9

    )

    axes[i].axis("off")

    print(f"\nImage {i+1}")

    print(f"Ground Truth Caption : {sample['caption']}")

    print(f"Predicted Class      : {sample['prediction']}")

    print(f"Similarity Score     : {sample['confidence']:.4f}")

    # --------------------------------------------------------
    # Very rough correctness check
    # --------------------------------------------------------

    caption = sample["caption"].lower()

    predicted_class = predicted.lower()

    if predicted_class in caption:

        correct += 1

for j in range(

    len(predictions),

    len(axes)

):

    axes[j].axis("off")

plt.tight_layout()

plt.savefig(

    "/content/drive/MyDrive/SoC_Task6/zero_shot.png",

    dpi=300,

    bbox_inches="tight"

)

plt.show()

print("\n" + "=" * 70)
print("Summary")
print("=" * 70)

print(f"Images Tested : {len(predictions)}")

print(

    f"Approximate Accuracy : "

    f"{100*correct/len(predictions):.1f}%"

)

print(

    "\nSaved figure to "

    "/content/drive/MyDrive/SoC_Task6/zero_shot.png"

)

print("\nDone.")