# -*- coding: utf-8 -*-
"""task6/train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nh-VRYD7_OweBm4XTJtCjL9hum23JwUv
"""

import os
import csv
import time
import math
import torch
import matplotlib.pyplot as plt

from tqdm import tqdm

from torch.utils.data import DataLoader, random_split
from torch.optim import AdamW
from torch.optim.lr_scheduler import LambdaLR

from task5_clip_model import CLIPStyleModel
from task6_dataset import (
    Flickr8kDataset,
    tokenizer,
    captions,
    image_dir,
)

# ============================================================
# Device
# ============================================================

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(f"Using device : {device}")

# ============================================================
# Configuration
# (Exactly as suggested in the handbook)
# ============================================================

config = {

    "batch_size": 128,

    "lr": 5e-4,

    "weight_decay": 0.05,

    "warmup_steps": 500,

    "total_steps": 10000,

    "grad_clip": 1.0,

    "projection_dim": 128,

    "embed_dim": 192,

    "image_size": 64,

    "patch_size": 8,

    "max_text_len": 32,

    "vit_depth": 4,

    "text_depth": 4,

    "n_head": 6,

    "dropout": 0.1,

    "val_every": 200

}

# ============================================================
# Dataset
# ============================================================

dataset = Flickr8kDataset(

    dataframe=captions,

    image_dir=image_dir,

    tokenizer=tokenizer,

    image_size=config["image_size"],

    max_length=config["max_text_len"],

    train=True

)

# 80 / 10 / 10 split

train_size = int(0.8 * len(dataset))

val_size = int(0.1 * len(dataset))

test_size = len(dataset) - train_size - val_size

generator = torch.Generator().manual_seed(42)

train_dataset, val_dataset, test_dataset = random_split(

    dataset,

    [train_size, val_size, test_size],

    generator=generator

)

# Validation transform

val_transform = Flickr8kDataset(

    dataframe=captions.iloc[:1],

    image_dir=image_dir,

    tokenizer=tokenizer,

    image_size=config["image_size"],

    max_length=config["max_text_len"],

    train=False

).transform

val_dataset.dataset.transform = val_transform

test_dataset.dataset.transform = val_transform

# ============================================================
# DataLoaders
# ============================================================

train_loader = DataLoader(

    train_dataset,

    batch_size=config["batch_size"],

    shuffle=True,

    num_workers=2,

    pin_memory=True

)

val_loader = DataLoader(

    val_dataset,

    batch_size=config["batch_size"],

    shuffle=False,

    num_workers=2,

    pin_memory=True

)

test_loader = DataLoader(

    test_dataset,

    batch_size=config["batch_size"],

    shuffle=False,

    num_workers=2,

    pin_memory=True

)

# ============================================================
# Model
# ============================================================

model = CLIPStyleModel(

    vocab_size=len(tokenizer.word2idx),

    embed_dim=config["embed_dim"],

    projection_dim=config["projection_dim"],

    n_head=config["n_head"],

    n_layer=config["vit_depth"],

    max_length=config["max_text_len"],

    dropout=config["dropout"]

).to(device)

optimizer = AdamW(

    model.parameters(),

    lr=config["lr"],

    weight_decay=config["weight_decay"]

)

# ============================================================
# Warmup + Cosine Scheduler
# ============================================================

def lr_lambda(step):

    if step < config["warmup_steps"]:

        return step / max(1, config["warmup_steps"])

    progress = (

        step - config["warmup_steps"]

    ) / (

        config["total_steps"] - config["warmup_steps"]

    )

    return 0.5 * (

        1 + math.cos(math.pi * progress)

    )

scheduler = LambdaLR(

    optimizer,

    lr_lambda

)

# ============================================================
# CSV Logger
# ============================================================

log_file = "training_log.csv"

if not os.path.exists(log_file):

    with open(log_file, "w", newline="") as f:

        writer = csv.writer(f)

        writer.writerow([
            "step",
            "train_loss",
            "val_loss",
            "learning_rate",
            "temperature",
            "gradient_norm",
            "time_per_step"
        ])


# ============================================================
# Checkpoint Utilities
# ============================================================

checkpoint_file = "checkpoint.pt"
best_model_file = "best_model.pt"

start_step = 0
best_val_loss = float("inf")


def save_checkpoint(step, best_val_loss):

    torch.save({

        "step": step,

        "model_state_dict": model.state_dict(),

        "optimizer_state_dict": optimizer.state_dict(),

        "scheduler_state_dict": scheduler.state_dict(),

        "best_val_loss": best_val_loss

    }, checkpoint_file)


def load_checkpoint():

    global start_step
    global best_val_loss

    if os.path.exists(checkpoint_file):

        checkpoint = torch.load(
            checkpoint_file,
            map_location=device
        )

        model.load_state_dict(
            checkpoint["model_state_dict"]
        )

        optimizer.load_state_dict(
            checkpoint["optimizer_state_dict"]
        )

        scheduler.load_state_dict(
            checkpoint["scheduler_state_dict"]
        )

        start_step = checkpoint["step"]

        best_val_loss = checkpoint["best_val_loss"]

        print(
            f"Resumed from step {start_step}"
        )


load_checkpoint()


# ============================================================
# Gradient Norm
# ============================================================

def get_gradient_norm(model):

    total_norm = 0.0

    for p in model.parameters():

        if p.grad is None:
            continue

        param_norm = p.grad.detach().data.norm(2)

        total_norm += param_norm.item() ** 2

    return total_norm ** 0.5


# ============================================================
# Validation
# ============================================================

@torch.no_grad()
def validate():

    model.eval()

    running_loss = 0.0

    for batch in val_loader:

        images = batch["image"].to(device)

        tokens = batch["tokens"].to(device)

        mask = batch["mask"].to(device)

        loss, _, _ = model(

            images,

            tokens,

            mask

        )

        running_loss += loss.item()

    model.train()

    return running_loss / len(val_loader)

# ============================================================
# Training
# ============================================================

model.train()

global_step = start_step

train_steps = []
train_losses = []

val_steps = []
val_losses = []

progress_bar = tqdm(
    total=config["total_steps"],
    initial=global_step,
    desc="Training"
)

while global_step < config["total_steps"]:

    for batch in train_loader:

        if global_step >= config["total_steps"]:
            break

        start_time = time.time()

        images = batch["image"].to(device)

        tokens = batch["tokens"].to(device)

        mask = batch["mask"].to(device)

        optimizer.zero_grad()

        loss, _, _ = model(

            images,

            tokens,

            mask

        )

        loss.backward()

        # --------------------------------------------
        # Gradient Clipping
        # --------------------------------------------

        grad_norm = torch.nn.utils.clip_grad_norm_(

            model.parameters(),

            config["grad_clip"]

        )

        optimizer.step()

        scheduler.step()

        global_step += 1

        lr = optimizer.param_groups[0]["lr"]

        temperature = (

            1.0 /

            model.loss_fn.logit_scale.exp()

        ).item()

        step_time = (

            time.time() - start_time

        )

        train_steps.append(

            global_step

        )

        train_losses.append(

            loss.item()

        )

        progress_bar.set_postfix(

            loss=f"{loss.item():.3f}",

            lr=f"{lr:.2e}",

            temp=f"{temperature:.4f}"

        )

        progress_bar.update(1)

        # ===================================================
        # Validation
        # ===================================================

        if global_step % config["val_every"] == 0:

            val_loss = validate()

            val_steps.append(

                global_step

            )

            val_losses.append(

                val_loss

            )

            print(

                f"\nStep {global_step}"

                f" | Train {loss.item():.4f}"

                f" | Val {val_loss:.4f}"

                f" | LR {lr:.2e}"

                f" | Temp {temperature:.4f}"

                f" | Grad {grad_norm:.3f}"

            )

            # --------------------------------------------
            # CSV Logging
            # --------------------------------------------

            with open(

                log_file,

                "a",

                newline=""

            ) as f:

                writer = csv.writer(f)

                writer.writerow([

                    global_step,

                    loss.item(),

                    val_loss,

                    lr,

                    temperature,

                    float(grad_norm),

                    step_time

                ])

            # --------------------------------------------
            # Best Model
            # --------------------------------------------

            if val_loss < best_val_loss:

                best_val_loss = val_loss

                torch.save(

                    model.state_dict(),

                    best_model_file

                )

                print(

                    "Best model saved."

                )

            # --------------------------------------------
            # Checkpoint
            # --------------------------------------------

            save_checkpoint(

                global_step,

                best_val_loss

            )

progress_bar.close()

print("\nTraining Complete.")

# ============================================================
# Test Evaluation
# ============================================================

print("\nLoading Best Model...")

model.load_state_dict(

    torch.load(

        best_model_file,

        map_location=device

    )

)

model.eval()

test_loss = 0.0

with torch.no_grad():

    progress = tqdm(

        test_loader,

        desc="Testing"

    )

    for batch in progress:

        images = batch["image"].to(device)

        tokens = batch["tokens"].to(device)

        mask = batch["mask"].to(device)

        loss, _, _ = model(

            images,

            tokens,

            mask

        )

        test_loss += loss.item()

        progress.set_postfix(

            loss=f"{loss.item():.4f}"

        )

test_loss /= len(test_loader)

print(

    f"\nFinal Test Loss : "

    f"{test_loss:.4f}"

)


# ============================================================
# Save Final Checkpoint
# ============================================================

torch.save(

    model.state_dict(),

    "last_model.pt"

)

print(

    "Last model saved."

)


# ============================================================
# Print Final Statistics
# ============================================================

final_lr = optimizer.param_groups[0]["lr"]

final_temperature = (

    1.0 /

    model.loss_fn.logit_scale.exp()

).item()

print("\nTraining Summary")

print("-" * 40)

print(

    f"Total Steps      : "

    f"{global_step}"

)

print(

    f"Best Val Loss    : "

    f"{best_val_loss:.4f}"

)

print(

    f"Final Test Loss  : "

    f"{test_loss:.4f}"

)

print(

    f"Final LR         : "

    f"{final_lr:.2e}"

)

print(

    f"Temperature      : "

    f"{final_temperature:.5f}"

)

print(

    f"Best Model       : "

    f"{best_model_file}"

)

print(

    f"Checkpoint       : "

    f"{checkpoint_file}"

)

print(

    f"CSV Log          : "

    f"{log_file}"

)

# ============================================================
# Training Curve
# ============================================================

plt.figure(figsize=(8, 5))

plt.plot(

    train_steps,

    train_losses,

    label="Training Loss",

    linewidth=1.5

)

plt.plot(

    val_steps,

    val_losses,

    label="Validation Loss",

    linewidth=2

)

plt.xlabel("Training Steps")

plt.ylabel("InfoNCE Loss")

plt.title("CLIP Training Curve")

plt.grid(True)

plt.legend()

plt.tight_layout()

plt.savefig(

    "training_curve.png",

    dpi=300

)

plt.show()

print(
    "\nTraining curve saved as training_curve.png"
)


# ============================================================
# Save Final Configuration
# ============================================================

torch.save(

    {

        "config": config,

        "best_val_loss": best_val_loss,

        "test_loss": test_loss,

        "steps": global_step

    },

    "training_summary.pt"

)

print(
    "Training summary saved."
)


# ============================================================
# Finished
# ============================================================

print("\n" + "=" * 60)
print("Training Finished Successfully")
print("=" * 60)

print(f"Total Training Steps : {global_step}")
print(f"Best Validation Loss : {best_val_loss:.4f}")
print(f"Final Test Loss      : {test_loss:.4f}")

print("\nGenerated Files")
print("-----------------------------")
print("best_model.pt")
print("last_model.pt")
print("checkpoint.pt")
print("training_curve.png")
print("training_log.csv")
print("training_summary.pt")

print("\nDone!")