# -*- coding: utf-8 -*-
"""task5/toy_alignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_RbsysmnN7j6UGf0Geq_IDlJtiMrhz2
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

class InfoNCELoss(nn.Module):

    def __init__(self, init_temperature=0.07):
        super().__init__()

        # Learnable log(1/tau)
        self.log_inv_tau = nn.Parameter(
            torch.tensor([1.0 / init_temperature]).log()
        )

    def forward(self, image_embeds, text_embeds):

        # Normalize embeddings
        image_embeds = F.normalize(image_embeds, dim=-1)
        text_embeds = F.normalize(text_embeds, dim=-1)

        # Clamp inverse temperature
        log_inv_tau = self.log_inv_tau.clamp(0, 4.6052)
        inv_tau = log_inv_tau.exp()

        # Similarity matrix
        logits = inv_tau * image_embeds @ text_embeds.T

        # Ground-truth labels are the diagonal
        N = image_embeds.size(0)
        labels = torch.arange(N, device=logits.device)

        # Image -> Text loss
        loss_i2t = F.cross_entropy(logits, labels)

        # Text -> Image loss
        loss_t2i = F.cross_entropy(logits.T, labels)

        # Symmetric CLIP loss
        return (loss_i2t + loss_t2i) / 2

# ----------------------------------------------------
# Device
# ----------------------------------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(42)

# ----------------------------------------------------
# Fixed random features
# ----------------------------------------------------
N = 32
input_dim = 192
projection_dim = 128

image_features = torch.randn(N, input_dim, device=device)
text_features = torch.randn(N, input_dim, device=device)

# ----------------------------------------------------
# Toy CLIP model
# ----------------------------------------------------
class ToyCLIP(nn.Module):

    def __init__(self):
        super().__init__()

        self.image_proj = nn.Linear(input_dim, projection_dim)

        self.text_proj = nn.Linear(input_dim, projection_dim)

        self.loss_fn = InfoNCELoss()

    def forward(self, image_features, text_features):

        image_embeds = self.image_proj(image_features)

        text_embeds = self.text_proj(text_features)

        loss = self.loss_fn(
            image_embeds,
            text_embeds
        )

        return loss, image_embeds, text_embeds


model = ToyCLIP().to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

# ----------------------------------------------------
# Training
# ----------------------------------------------------
num_steps = 500

losses = []

for step in range(num_steps):

    loss, image_embeds, text_embeds = model(
        image_features,
        text_features
    )

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    losses.append(loss.item())

    if (step + 1) % 50 == 0:
        print(
            f"Step {step+1:3d} | Loss = {loss.item():.4f}"
        )

# ----------------------------------------------------
# Plot training loss
# ----------------------------------------------------
plt.figure(figsize=(6,4))

plt.plot(losses)

plt.xlabel("Training Step")
plt.ylabel("InfoNCE Loss")
plt.title("Toy Alignment Training Loss")

plt.grid(True)

plt.tight_layout()

plt.savefig("toy_loss_curve.png")

plt.show()

# ----------------------------------------------------
# Similarity matrix after training
# ----------------------------------------------------
with torch.no_grad():

    image_embeds = F.normalize(
        model.image_proj(image_features),
        dim=-1
    )

    text_embeds = F.normalize(
        model.text_proj(text_features),
        dim=-1
    )

    similarity = image_embeds @ text_embeds.T

    # Average diagonal similarity
    # Average diagonal similarity
    diag_mean = similarity.diag().mean().item()

    # Average off-diagonal similarity
    mask = ~torch.eye(
        similarity.size(0),
        dtype=torch.bool,
        device=similarity.device
    )

    off_diag_mean = similarity[mask].mean().item()

    print(f"Average Diagonal Similarity     : {diag_mean:.4f}")
    print(f"Average Off-Diagonal Similarity : {off_diag_mean:.4f}")
plt.figure(figsize=(6,6))

plt.imshow(
    similarity.cpu(),
    cmap="viridis"
)

plt.colorbar()

plt.title("Similarity Matrix After Training")

plt.xlabel("Text Features")

plt.ylabel("Image Features")

plt.tight_layout()

plt.savefig("similarity_matrix.png")

plt.show()

print("\nFinal Loss:", losses[-1])