# -*- coding: utf-8 -*-
"""task5/loss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pabpPusSEcaMDK4LfFvNVkoRboJ9rwfB
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class InfoNCELoss(nn.Module):

    def __init__(self, init_temperature=0.07):
        super().__init__()

        # Learnable log(1/tau)
        self.log_inv_tau = nn.Parameter(
            torch.tensor([1.0 / init_temperature]).log()
        )

    def forward(self, image_embeds, text_embeds):

        # Normalize embeddings
        image_embeds = F.normalize(image_embeds, dim=-1)
        text_embeds = F.normalize(text_embeds, dim=-1)

        # Clamp inverse temperature
        log_inv_tau = self.log_inv_tau.clamp(0, 4.6052)
        inv_tau = log_inv_tau.exp()

        # Similarity matrix
        logits = inv_tau * image_embeds @ text_embeds.T

        # Ground-truth labels are the diagonal
        N = image_embeds.size(0)
        labels = torch.arange(N, device=logits.device)

        # Image -> Text loss
        loss_i2t = F.cross_entropy(logits, labels)

        # Text -> Image loss
        loss_t2i = F.cross_entropy(logits.T, labels)

        # Symmetric CLIP loss
        return (loss_i2t + loss_t2i) / 2