# -*- coding: utf-8 -*-
"""task5/test_loss

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AI6cyoTfOvN9jF3beTgVuBR558MBg6s
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
class InfoNCELoss(nn.Module):
 def __init__(self, init_temperature=0.07):
    super().__init__()
    # Learnable log-temperature, as in CLIP
    # log(1/0.07) ~ 2.659
    self.log_inv_tau = nn.Parameter(
    torch.tensor([1.0 / init_temperature]).log()
 )
 def forward(self, image_embeds, text_embeds):
 # Normalize to unit sphere
    image_embeds = F.normalize(image_embeds, dim=-1)
    text_embeds = F.normalize(text_embeds, dim=-1)
    # Clamp temperature for stability (CLIP does this)
    # Prevents log_inv_tau from blowing up
    log_inv_tau = self.log_inv_tau.clamp(0, 4.6052) # log(100)
    inv_tau = log_inv_tau.exp()
    # Similarity matrix (N, N)
    logits = inv_tau * image_embeds @ text_embeds.T
    # Targets are the diagonal
    N = image_embeds.size(0)
    labels = torch.arange(N, device=logits.device)
    loss_i2t = F.cross_entropy(logits, labels)
    loss_t2i = F.cross_entropy(logits.T, labels)
    return (loss_i2t + loss_t2i) / 2


torch.manual_seed(42)

N = 32
D = 128

loss_fn = InfoNCELoss()

# -------------------------
# Test 1: Identical embeddings
# -------------------------
embeds = torch.randn(N, D)
loss = loss_fn(embeds, embeds)

print(f"Test 1 Loss: {loss.item():.4f}")
print("Expected: Close to 0\n")

# -------------------------
# Test 2: Random embeddings
# -------------------------
image_embeds = torch.randn(N, D)
text_embeds = torch.randn(N, D)

loss = loss_fn(image_embeds, text_embeds)

print(f"Test 2 Loss: {loss.item():.4f}")
print(f"Expected: ≈ {math.log(N):.4f}\n")

# -------------------------
# Test 3: Half aligned
# -------------------------
image_embeds = torch.randn(N, D)
text_embeds = torch.randn(N, D)

text_embeds[:N//2] = image_embeds[:N//2]

loss = loss_fn(image_embeds, text_embeds)

print(f"Test 3 Loss: {loss.item():.4f}")
print(f"Expected: Between 0 and {math.log(N):.4f}\n")

# -------------------------
# Test 4: Gradient check
# -------------------------
image_embeds = torch.randn(N, D, requires_grad=True)
text_embeds = torch.randn(N, D, requires_grad=True)

loss = loss_fn(image_embeds, text_embeds)
loss.backward()

print("Gradient Check") #all gradients should be able to flow backwards to the learnable parameters.
print(f"log_inv_tau.grad : {loss_fn.log_inv_tau.grad is not None}")
print(f"image_embeds.grad: {image_embeds.grad is not None}")
print(f"text_embeds.grad : {text_embeds.grad is not None}")